config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
  end
  get 'search_result', :to => 'posts#search_result'

  resources :home
  get '/explore', :to => 'home#explore'
  get 'search', :to => 'home#search'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :activities
  belongs_to :user
  acts_as_votable

  include PgSearch
  pg_search_scope :search_country, :against => [:country]

  validates :image, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def country_name
     c = ISO3166::Country[self.country]
     return c.translations[I18n.locale.to_s] || c.name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:login]

  validates :username, :presence => true, :uniqueness => {:case_sensitive => false}

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  attr_accessor :login

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(user)
    posts_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!

  def index
  end

  #/explore: my own route!!! This shows ALL POSTS FROM ALL USERS, even without log in
  def explore
    @posts = Post.all
    @activity = Activity.all
    @user = User.all
  end

  #/posts/id shows individual post
  def show
    @post = Post.find(params[:id])
    @activity = @post.activity
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:explore, :search, :search_result]

  #/posts: shows all posts that have been created on 1 page
  def index
    @posts = current_user.posts
    # @posts = Post.all
    @activity = Activity.all
  end

  #upvote
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  #simple search
  def search
    
  end

  def search_result
    @results = Post.search_country(params[:search])
  end

  #/new: form that will accept user inputs
  def new
    @post = Post.new
    @activity = Activity.new
    # @post.user_id = current_user.id
  end
  #create: clicking of upload button to allow creation of new entry. Redirects to new post
  def create
    @activity = params[:activities] #getting input from isolated form field
    my_params = post_params
    my_params[:user_id] = current_user.id
    if @post = Post.create(my_params) #if object creation is true, go on to create Activity

      @activities = Activity.create(:name => @activity, :post_id => @post.id)
      #when creating new Activity, pass 2 methods @activity and @post values into Activity model

      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
    flash.now[:alert] = "Your new post could not be created!"
    render :new
    end
  #insert activity here
  end

  #/posts/id shows individual post
  def show
    @post = Post.find(params[:id])
    @activity = @post.activities
  end

  #/posts/id/edit
  def edit
    @post = Post.find(params[:id])
    @activity = Activity.find(params[:id])
  end
  #clicking button to update: actually perform an update that touches our database. It’s very similar to our create action but rather than creating, we’re UPDATING
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    @activity = Activity.find(params[:id])
    @activity.update(name: params[:activities])
    flash[:success] = "Your post has been updated!"
    redirect_to(post_path(@post))
  end

  #deleting a post
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    flash[:success] = "Your post has been deleted!"
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:image, :title, :description, :budget, :country)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/explore.erb
<h1 class = "all_headers"><i class="fa fa-smile-o"></i> hello stranger </h2>

<% @posts.each do |post| %>
<div class="posts-wrapper row">
  <div class="posts">


      <div class="post-head">
        <p><i class="fa fa-user"></i> <strong><%= post.user.username %></strong></p>
        <p>Title: <%= post.title %></p>
        <p>Created <i><%= time_ago_in_words(post.created_at) %> ago</i></p>
      </div>

      <div class="caption">
        <p>This was in <i><%= post.country_name %></i></p>
        <p>I spent S$ <i><%= post.budget %></i></p>
        <p>Category: <%= Activity.find_by(post_id: post.id).name %></p>
      </div>

      <p class="image center-block"><%= link_to (image_tag post.image.url(:medium)), post_path(post) %></p>

      <p class = "like_globe"><%= link_to like_post_path(post), method: :put do %><i class="fa fa-globe fa-spin fa-2x"></i> <%= post.get_upvotes.size %><% end %> karma points</p>

      <p class = "read"><%= post.description%></p>

    </div>
  </div>
  <% end %>

app/views/home/index.erb
<!-- <%= image_tag("home_index_background.jpg") %> -->
<div class = "home_landing">

  <h1 class = "main-title"><i class="fa fa-globe fa-spin"></i><strong> TRIP LOBANGS <strong></i></h1>

  <h2 class = "landing_page_nav">
      <a href = "/posts"><i class="fa fa-user-secret fa-2x"></i> MY LOBANGS</a>
      <a href = "/posts/new"><i class="fa fa-plus-square fa-2x"></i> NEW LOBANG</a>
      <a href = "/explore"><i class="fa fa-binoculars fa-2x"></i> EXPLORE</a>
  </h2>
  <hr>
  <div class = "landing_page_text">
    <h2>Don't just take photos when you travel. Be a good lobang.<br>Log your travel experiences here for others on similar adventures.<br><br>No more #FOMO. No more #BOJIO.</h2>
      <div id = "landing_page_instructions">
        <h2>1. Register/Log in</h2>
        <h2>2. Create travel tip</h2>
        <h2>3. Blow minds</h2>
        <h2>4. Get mind blown</h2>
        <h2>Or... you could <i class="fa fa-eye"></i></i> <strong><%= link_to "find Wally", search_path %></h2></strong>
      </div>
  </div>
</div>

app/views/home/search.erb
<div id = "search_page">

  <h1 class = "all_headers"><i class="fa fa-plane"></i> People don't take trips. Trips take people...</h1>

  <div class = "explore search">
    <%= form_tag(search_result_path, :method => "get", id: "search-form") do %>
    <i class="fa fa-search">  <%= text_field_tag :search, params[:search], placeholder: "Search by Country" %></i>
    <%= submit_tag "Search" %>
    <% end %>
  </div>

</div>

app/views/home/show.erb
<div class="posts-wrapper row">

  <div class="post">

    <div class="post-head">
      <p><i class="fa fa-user"></i> <strong><%= @post.user.username %></strong></p>
      <p>Title: <%= @post.title %></p>
      <p>Created <i><%= time_ago_in_words(@post.created_at) %> ago</i></p>
    </div>

    <div class="caption">
      <p>This was in <i><%= @post.country_name %></i></p>
      <p>I spent S$ <i><%= @post.budget %></i></p>
    <p>Category: <i><%= @activity.first.name %></i></p>
  </div>

    <p class="image center-block"><%= link_to (image_tag @post.image.url(:medium)) %></p>

    <p class="description">What went down: <%= @post.description%></p>

    <p class = "like-globe"><%= link_to like_post_path(@post), method: :put do %><i class="fa fa-globe fa-spin fa-2x"></i> <%= @post.get_upvotes.size %><% end %> karma points</p>

    <!-- back and edit functions -->

  </div>
</div>
</div>

<div class="text-center">
<%= link_to "Back", posts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trip Lobangs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation bar -->
  <nav class="navbar navbar-default">
    <div class="navbar-container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to "Home", root_path, :id => "home_button"%>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
        <% if !user_signed_in? %>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                  <li class="<%= "active" if current_page?("/users/sign_in")  %>">
                    <%= link_to "Sign In", new_user_session_path, :id => "sign_in"%>
                  </li>
                  <li>
                    <%= link_to "Register", new_user_registration_path, :id => "register" %>
                  </li>
                </ul>
            </div>
        <% else %>
            <div class="navbar-right">
              <p class="navbar-text">
                  <i class="fa fa-user"></i> Signed in as <%= current_user.username %>
              </p>
              <ul class="nav navbar-nav">
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete, :id => "signout" %>
                </li>
              </ul>
            </div>
        <% end %>
      </div>

    </div>
  </nav>


  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/edit.erb
<h1 class = "all_headers"><i class="fa fa-pencil fa-2x"></i>  Edit</h1>

<div class="form-wrapper">

  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>

    <div class="form01">
      <%= f.input :title %>
    </div>

    <div class="form01">
      <%= f.input :image %>
    </div>

    <div class="form01">
      <%= f.input :country, as: :country %>
    </div>

    <div class="form01">
      <%= f.input :budget %>
    </div>

    <div class="form01">
      <%= f.input :description %>
    </div>

    <div class="radio">
      <input type="radio" name="activities" value="Accommodation">Accommodation<br>
      <input type="radio" name="activities" value="Food/Drinks">Food/Drinks<br>
      <input type="radio" name="activities" value="Nature">Nature<br>
      <input type="radio" name="activities" value="Place of Interest">Place of Interest<br>
      <input type="radio" name="activities" value="Others">Others<br></p>
    </div>

    <div class="form01">
      <%= f.button :submit, class: 'btn-success' %>
    </div>

  <% end %>

  <!-- delete function -->
  <div>
    <%= link_to "Delete Post", post_path(@post.id), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    |
    <%= link_to "Cancel", posts_path %>
  </div>

</div>

app/views/posts/index.erb
<h1 class = "all_headers"><i class="fa fa-user-secret"></i> MY LOBANGS</h1>

<% @posts.each do |post| %>
<div class="posts-wrapper row">
  <div class="posts">


    <div class="post-head">
      <p><i class="fa fa-user"></i> <strong><%= post.user.username %></strong></p>
      <p>Title: <%= post.title %></p>
      <p>Created <i><%= time_ago_in_words(post.created_at) %> ago</i></p>
    </div>

    <div class="caption">
      <p>This was in <i><%= post.country_name %></i></p>
      <p>I spent S$ <i><%= post.budget %></i></p>

        <% if post.activities.first
              @a = post.activities.first.name
            elsif
              @a = 'None'
            end
        %>
      <p>Category: <i><%= @a %></i></p>
      <!-- from #@activity, get the post belonging to it and return the name of activity.post_id.name -->
    </div>

    <p class="image center-block"><%= link_to (image_tag post.image.url(:medium)), post_path(post) %></p>

    <p class = "like_globe"><%= link_to like_post_path(post), method: :put do %><i class="fa fa-globe fa-spin fa-2x"></i> <%= post.get_upvotes.size %><% end %> karma points</p>

    <p class = "read"><a href="<%= post_path(post.id) %>">(Read more...)</a></p>

  </div>
</div>
<% end %>

app/views/posts/new.erb
<h1 class = "all_headers"><i class="fa fa-plus"></i>  New</h1>

<div class="form-wrapper">

  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form01">
      <%= f.input :title %>
    </div>

    <div class="form01">
      <%= f.input :image %>
    </div>

    <div class="form01">
      <%= f.input :country, as: :country %>
    </div>

    <div class="form01">
      <%= f.input :budget %>
    </div>

    <div class="form01">
      <%= f.input :description %>
    </div>

    <div class="radio">
      <input type="radio" name="activities" value="Accommodation">Accommodation<br>
      <input type="radio" name="activities" value="Food/Drinks">Food/Drinks<br>
      <input type="radio" name="activities" value="Nature">Nature<br>
      <input type="radio" name="activities" value="Place of Interest">Place of Interest<br>
      <input type="radio" name="activities" value="Others">Others<br></p>
    </div>

    <div class="form01">
      <%= f.button :submit, class: 'btn-success' %>
    </div>

  <% end %>

</div>

app/views/posts/search_result.erb
<h1 class = "all_headers"><i class="fa fa-diamond"></i></i>  We found some gems</h1>

<% @results.each do |result| %>
  <div class="posts-wrapper row">
    <div class="posts">

      <div class="post-head">
        <p><i class="fa fa-user"></i> <strong><%= result.user.username %></strong></p>
        <p>Title: <%= result.title %></p>
        <p>Created <%= time_ago_in_words(result.created_at) %> ago</p>
      </div>

      <div class="caption">
        <p>This was in <i><%= result.country_name %></i></p>
        <p>I spent S$ <i><%= result.budget %></i></p>
        <p>Category: <i><%= result.activities.first.name %></i></p>
      </div>

    <p class="image center-block"><%= link_to (image_tag result.image.url(:medium)), post_path(result) %></p>

    <p class="description">What went down: <%= result.description%></p>

    <p class = "like_globe"><%= link_to like_post_path(result), method: :put do %><i class="fa fa-globe fa-spin fa-2x"></i> <%= result.get_upvotes.size %><% end %> karma points</p>

  </div>
</div>
<% end %>

app/views/posts/show.erb
<div class="posts-wrapper row">

  <div class="post">

    <div class="post-head">
      <p><i class="fa fa-user"></i> <strong><%= @post.user.username %></strong></p>
      <p>Title: <%= @post.title %></p>
      <p>Created <i><%= time_ago_in_words(@post.created_at) %> ago</i></p>
    </div>

    <div class="caption">
      <p>This was in <strong><i><%= @post.country_name %></i></strong></p>
      <p>I spent <strong>S$<i><%= @post.budget %></i></strong></p>
      <p>Category: <strong><i><%= @activity.first.name %></i></strong></p>
  </div>

    <p class="image center-block"><%= link_to (image_tag @post.image.url(:medium)) %></p>

    <p class="description"><i>What happened:</i> <%= @post.description%></p>

    <p class = "like_globe"><%= link_to like_post_path(@post), method: :put do %><i class="fa fa-globe fa-spin fa-2x"></i> <%= @post.get_upvotes.size %><% end %> karma points</p>

  </div>

</div>

<!-- back and edit functions -->
</div>
<div class="text-center">
<%= link_to "Back", posts_path %>
|
<%= link_to "Edit Post", edit_post_path(@post) %>
</div>